dist: bionic

language: cpp

sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then sudo apt-get update -qq ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then sudo apt-get install -y pkg-config ; fi
  - git -C .. clone https://github.com/g-maxime/ZenLib.git
  - mkdir ../ZenLib/Build && pushd ../ZenLib/Build && cmake ../Project/CMake && make VERBOSE=1 && sudo make install && popd
  - git -C .. clone https://github.com/MediaArea/MediaInfoLib.git
  - mkdir ../MediaInfoLib/Build && pushd ../MediaInfoLib/Build && CXXFLAGS=-DMEDIAINFO_LIBCURL_NO cmake -DBUILD_SHARED_LIBS=ON ../Project/CMake && make && sudo make install && popd

script:
  - cd Project/GNU/CLI/ && sh autogen.sh && ./configure && make &&
    mkdir ../../CMake/Build && cd ../../CMake/Build && cmake .. && make
