language: cpp

sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then sudo apt-get update -qq ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then sudo apt-get install -y pkg-config libxml2-utils libfreetype6-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then brew update ; true ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then brew install freetype ; true ; fi

  - git -C .. clone --depth=1 https://git.ffmpeg.org/ffmpeg.git
  - pushd ../ffmpeg && ./configure --prefix=.. --disable-doc --disable-x86asm --disable-ffplay --disable-ffprobe --enable-static --disable-everything --enable-protocol=file --enable-libfreetype --enable-indev=lavfi --enable-filter=testsrc2,scale,aresample,sine,drawtext --enable-demuxer=dv --enable-muxer=dv --enable-encoder=rawvideo,dvvideo,dvaudio,pcm_* --enable-decoder=rawvideo,dvvideo,dvaudio,pcm_* && make && popd
  - cp ../ffmpeg/ffmpeg Project/GNU/CLI/
  - git -C .. clone --depth=1 https://github.com/MediaArea/ZenLib.git
  - pushd ../ZenLib/Project/GNU/Library && sh autogen.sh && ./configure --prefix=/usr/local && make && sudo make install && popd
  - git -C .. clone --depth=1 https://github.com/MediaArea/MediaInfoLib.git
  - pushd ../MediaInfoLib/Project/GNU/Library && sh autogen.sh && ./configure --prefix=/usr/local && make && sudo make install && popd

script: cd Project/GNU/CLI/ && sh autogen.sh && ./configure && make && make clone_testing_files && make check
