#! /bin/sh

if qmake --version >/dev/null 2>&1
then
    qmake $*
elif qmake-qt5 --version >/dev/null 2>&1
then
    qmake-qt5 $*
elif qmake5 --version >/dev/null 2>&1
then
    qmake5 $*
else
    echo qmake not found, please install Qt development package
    exit
fi
