name: Checks

on: [push, pull_request]

jobs:

  Job:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: OS packets
        run: | 
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y pkg-config libxml2-utils libfreetype-dev libharfbuzz-dev libraw1394-dev libavc1394-dev libiec61883-dev
          fi
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install libtool automake freetype
          fi
      - name: FFmpeg
        run: | 
          git -C .. clone --depth=1 https://git.ffmpeg.org/ffmpeg.git
          pushd ../ffmpeg && ./configure --prefix=.. --disable-doc --disable-x86asm --disable-ffplay --disable-ffprobe --enable-static --disable-everything --enable-protocol=file --enable-libfreetype --enable-libharfbuzz --enable-indev=lavfi --enable-filter=testsrc2,scale,aresample,sine,drawtext,colorspace --enable-demuxer=dv --enable-muxer=dv --enable-encoder=rawvideo,wrapped_avframe,dvvideo,dvaudio,pcm_* --enable-decoder=rawvideo,wrapped_avframe,dvvideo,dvaudio,pcm_* && make && popd
          cp ../ffmpeg/ffmpeg Project/GNU/CLI/
      - name: ZenLib
        run: |
            git -C .. clone --depth=1 https://github.com/MediaArea/ZenLib.git
            pushd ../ZenLib/Project/GNU/Library && sh autogen.sh && ./configure --prefix=/usr/local && make && sudo make install && popd
      - name: MediaInfoLib
        run: |
            git -C .. clone --depth=1 https://github.com/MediaArea/MediaInfoLib.git
            pushd ../MediaInfoLib/Project/GNU/Library && sh autogen.sh && ./configure --prefix=/usr/local && make && sudo make install && popd
      - name: Configure
        run: | 
          cd Project/GNU/CLI
          sh autogen.sh
          ./configure
      - name: Compile
        run: | 
          cd Project/GNU/CLI
          make
      - name: Get check files
        run: | 
          cd Project/GNU/CLI
          make clone_testing_files
      - name: Check
        run: | 
          cd Project/GNU/CLI
          make check
